/*
Navicat MySQL Data Transfer

Source Server         : 圣妖传9998后台数据库
Source Server Version : 50615
Source Host           : 123.59.119.187:51888
Source Database       : syz_admin

Target Server Type    : MYSQL
Target Server Version : 50615
File Encoding         : 65001

Date: 2018-08-09 13:59:53
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `t_cfg_server_type`
-- ----------------------------
DROP TABLE IF EXISTS `t_cfg_server_type`;
CREATE TABLE `t_cfg_server_type` (
  `serverTypeId` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `serverTypeChineseName` varchar(255) DEFAULT NULL,
  `serverTypeVietnameseName` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`serverTypeId`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of t_cfg_server_type
-- ----------------------------
INSERT INTO `t_cfg_server_type` VALUES ('1', 'OPS服务器', 'OPS服务器');
INSERT INTO `t_cfg_server_type` VALUES ('2', '资源服务器', '资源服务器');
INSERT INTO `t_cfg_server_type` VALUES ('3', '游戏服务器', '游戏服务器');
INSERT INTO `t_cfg_server_type` VALUES ('4', '跨服服务器', '跨服服务器');

-- ----------------------------
-- Table structure for `t_cfg_skill`
-- ----------------------------
DROP TABLE IF EXISTS `t_cfg_skill`;
CREATE TABLE `t_cfg_skill` (
  `TalentId` int(10) NOT NULL COMMENT '天赋id',
  `Name` varchar(255) DEFAULT NULL COMMENT '天赋名'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of t_cfg_skill
-- ----------------------------
INSERT INTO `t_cfg_skill` VALUES ('1', '重斩Lv1');
INSERT INTO `t_cfg_skill` VALUES ('2', '重斩Lv2');
INSERT INTO `t_cfg_skill` VALUES ('3', '重斩Lv3');
INSERT INTO `t_cfg_skill` VALUES ('4', '重斩Lv4');
INSERT INTO `t_cfg_skill` VALUES ('5', '重斩Lv5');
INSERT INTO `t_cfg_skill` VALUES ('6', '重斩Lv6');
INSERT INTO `t_cfg_skill` VALUES ('7', '重斩Lv7');
INSERT INTO `t_cfg_skill` VALUES ('8', '重斩Lv8');
INSERT INTO `t_cfg_skill` VALUES ('9', '重斩Lv9');
INSERT INTO `t_cfg_skill` VALUES ('10', '重斩Lv10');
INSERT INTO `t_cfg_skill` VALUES ('21', '击晕Lv1');
INSERT INTO `t_cfg_skill` VALUES ('22', '击晕Lv2');
INSERT INTO `t_cfg_skill` VALUES ('23', '击晕Lv3');
INSERT INTO `t_cfg_skill` VALUES ('24', '击晕Lv4');
INSERT INTO `t_cfg_skill` VALUES ('25', '击晕Lv5');
INSERT INTO `t_cfg_skill` VALUES ('26', '击晕Lv6');
INSERT INTO `t_cfg_skill` VALUES ('27', '击晕Lv7');
INSERT INTO `t_cfg_skill` VALUES ('28', '击晕Lv8');
INSERT INTO `t_cfg_skill` VALUES ('29', '击晕Lv9');
INSERT INTO `t_cfg_skill` VALUES ('30', '击晕Lv10');
INSERT INTO `t_cfg_skill` VALUES ('41', '跳斩Lv1');
INSERT INTO `t_cfg_skill` VALUES ('42', '跳斩Lv2');
INSERT INTO `t_cfg_skill` VALUES ('43', '跳斩Lv3');
INSERT INTO `t_cfg_skill` VALUES ('44', '跳斩Lv4');
INSERT INTO `t_cfg_skill` VALUES ('45', '跳斩Lv5');
INSERT INTO `t_cfg_skill` VALUES ('46', '跳斩Lv6');
INSERT INTO `t_cfg_skill` VALUES ('47', '跳斩Lv7');
INSERT INTO `t_cfg_skill` VALUES ('48', '跳斩Lv8');
INSERT INTO `t_cfg_skill` VALUES ('49', '跳斩Lv9');
INSERT INTO `t_cfg_skill` VALUES ('50', '跳斩Lv10');
INSERT INTO `t_cfg_skill` VALUES ('61', '旋风斩Lv1');
INSERT INTO `t_cfg_skill` VALUES ('62', '旋风斩Lv2');
INSERT INTO `t_cfg_skill` VALUES ('63', '旋风斩Lv3');
INSERT INTO `t_cfg_skill` VALUES ('64', '旋风斩Lv4');
INSERT INTO `t_cfg_skill` VALUES ('65', '旋风斩Lv5');
INSERT INTO `t_cfg_skill` VALUES ('66', '旋风斩Lv6');
INSERT INTO `t_cfg_skill` VALUES ('67', '旋风斩Lv7');
INSERT INTO `t_cfg_skill` VALUES ('68', '旋风斩Lv8');
INSERT INTO `t_cfg_skill` VALUES ('69', '旋风斩Lv9');
INSERT INTO `t_cfg_skill` VALUES ('70', '旋风斩Lv10');
INSERT INTO `t_cfg_skill` VALUES ('151', '战斗之吼Lv1');
INSERT INTO `t_cfg_skill` VALUES ('152', '战斗之吼Lv2');
INSERT INTO `t_cfg_skill` VALUES ('153', '战斗之吼Lv3');
INSERT INTO `t_cfg_skill` VALUES ('154', '战斗之吼Lv4');
INSERT INTO `t_cfg_skill` VALUES ('155', '战斗之吼Lv5');
INSERT INTO `t_cfg_skill` VALUES ('156', '战斗之吼Lv6');
INSERT INTO `t_cfg_skill` VALUES ('157', '战斗之吼Lv7');
INSERT INTO `t_cfg_skill` VALUES ('158', '战斗之吼Lv8');
INSERT INTO `t_cfg_skill` VALUES ('159', '战斗之吼Lv9');
INSERT INTO `t_cfg_skill` VALUES ('160', '战斗之吼Lv10');
INSERT INTO `t_cfg_skill` VALUES ('171', '警示之吼Lv1');
INSERT INTO `t_cfg_skill` VALUES ('172', '警示之吼Lv2');
INSERT INTO `t_cfg_skill` VALUES ('173', '警示之吼Lv3');
INSERT INTO `t_cfg_skill` VALUES ('174', '警示之吼Lv4');
INSERT INTO `t_cfg_skill` VALUES ('175', '警示之吼Lv5');
INSERT INTO `t_cfg_skill` VALUES ('176', '警示之吼Lv6');
INSERT INTO `t_cfg_skill` VALUES ('177', '警示之吼Lv7');
INSERT INTO `t_cfg_skill` VALUES ('178', '警示之吼Lv8');
INSERT INTO `t_cfg_skill` VALUES ('179', '警示之吼Lv9');
INSERT INTO `t_cfg_skill` VALUES ('180', '警示之吼Lv10');
INSERT INTO `t_cfg_skill` VALUES ('191', '血性之吼Lv1');
INSERT INTO `t_cfg_skill` VALUES ('192', '血性之吼Lv2');
INSERT INTO `t_cfg_skill` VALUES ('193', '血性之吼Lv3');
INSERT INTO `t_cfg_skill` VALUES ('194', '血性之吼Lv4');
INSERT INTO `t_cfg_skill` VALUES ('195', '血性之吼Lv5');
INSERT INTO `t_cfg_skill` VALUES ('196', '血性之吼Lv6');
INSERT INTO `t_cfg_skill` VALUES ('197', '血性之吼Lv7');
INSERT INTO `t_cfg_skill` VALUES ('198', '血性之吼Lv8');
INSERT INTO `t_cfg_skill` VALUES ('199', '血性之吼Lv9');
INSERT INTO `t_cfg_skill` VALUES ('200', '血性之吼Lv10');
INSERT INTO `t_cfg_skill` VALUES ('211', '狂暴怒吼Lv1');
INSERT INTO `t_cfg_skill` VALUES ('212', '狂暴怒吼Lv2');
INSERT INTO `t_cfg_skill` VALUES ('213', '狂暴怒吼Lv3');
INSERT INTO `t_cfg_skill` VALUES ('214', '狂暴怒吼Lv4');
INSERT INTO `t_cfg_skill` VALUES ('215', '狂暴怒吼Lv5');
INSERT INTO `t_cfg_skill` VALUES ('216', '狂暴怒吼Lv6');
INSERT INTO `t_cfg_skill` VALUES ('217', '狂暴怒吼Lv7');
INSERT INTO `t_cfg_skill` VALUES ('218', '狂暴怒吼Lv8');
INSERT INTO `t_cfg_skill` VALUES ('219', '狂暴怒吼Lv9');
INSERT INTO `t_cfg_skill` VALUES ('220', '狂暴怒吼Lv10');
INSERT INTO `t_cfg_skill` VALUES ('301', '圣光斩Lv1');
INSERT INTO `t_cfg_skill` VALUES ('302', '圣光斩Lv2');
INSERT INTO `t_cfg_skill` VALUES ('303', '圣光斩Lv3');
INSERT INTO `t_cfg_skill` VALUES ('304', '圣光斩Lv4');
INSERT INTO `t_cfg_skill` VALUES ('305', '圣光斩Lv5');
INSERT INTO `t_cfg_skill` VALUES ('306', '圣光斩Lv6');
INSERT INTO `t_cfg_skill` VALUES ('307', '圣光斩Lv7');
INSERT INTO `t_cfg_skill` VALUES ('308', '圣光斩Lv8');
INSERT INTO `t_cfg_skill` VALUES ('309', '圣光斩Lv9');
INSERT INTO `t_cfg_skill` VALUES ('310', '圣光斩Lv10');
INSERT INTO `t_cfg_skill` VALUES ('321', '牺牲Lv1');
INSERT INTO `t_cfg_skill` VALUES ('322', '牺牲Lv2');
INSERT INTO `t_cfg_skill` VALUES ('323', '牺牲Lv3');
INSERT INTO `t_cfg_skill` VALUES ('324', '牺牲Lv4');
INSERT INTO `t_cfg_skill` VALUES ('325', '牺牲Lv5');
INSERT INTO `t_cfg_skill` VALUES ('326', '牺牲Lv6');
INSERT INTO `t_cfg_skill` VALUES ('327', '牺牲Lv7');
INSERT INTO `t_cfg_skill` VALUES ('328', '牺牲Lv8');
INSERT INTO `t_cfg_skill` VALUES ('329', '牺牲Lv9');
INSERT INTO `t_cfg_skill` VALUES ('330', '牺牲Lv10');
INSERT INTO `t_cfg_skill` VALUES ('341', '祝福之锤Lv1');
INSERT INTO `t_cfg_skill` VALUES ('342', '祝福之锤Lv2');
INSERT INTO `t_cfg_skill` VALUES ('343', '祝福之锤Lv3');
INSERT INTO `t_cfg_skill` VALUES ('344', '祝福之锤Lv4');
INSERT INTO `t_cfg_skill` VALUES ('345', '祝福之锤Lv5');
INSERT INTO `t_cfg_skill` VALUES ('346', '祝福之锤Lv6');
INSERT INTO `t_cfg_skill` VALUES ('347', '祝福之锤Lv7');
INSERT INTO `t_cfg_skill` VALUES ('348', '祝福之锤Lv8');
INSERT INTO `t_cfg_skill` VALUES ('349', '祝福之锤Lv9');
INSERT INTO `t_cfg_skill` VALUES ('350', '祝福之锤Lv10');
INSERT INTO `t_cfg_skill` VALUES ('361', '天堂之拳Lv1');
INSERT INTO `t_cfg_skill` VALUES ('362', '天堂之拳Lv2');
INSERT INTO `t_cfg_skill` VALUES ('363', '天堂之拳Lv3');
INSERT INTO `t_cfg_skill` VALUES ('364', '天堂之拳Lv4');
INSERT INTO `t_cfg_skill` VALUES ('365', '天堂之拳Lv5');
INSERT INTO `t_cfg_skill` VALUES ('366', '天堂之拳Lv6');
INSERT INTO `t_cfg_skill` VALUES ('367', '天堂之拳Lv7');
INSERT INTO `t_cfg_skill` VALUES ('368', '天堂之拳Lv8');
INSERT INTO `t_cfg_skill` VALUES ('369', '天堂之拳Lv9');
INSERT INTO `t_cfg_skill` VALUES ('370', '天堂之拳Lv10');
INSERT INTO `t_cfg_skill` VALUES ('451', '冰锥术Lv1');
INSERT INTO `t_cfg_skill` VALUES ('452', '冰锥术Lv2');
INSERT INTO `t_cfg_skill` VALUES ('453', '冰锥术Lv3');
INSERT INTO `t_cfg_skill` VALUES ('454', '冰锥术Lv4');
INSERT INTO `t_cfg_skill` VALUES ('455', '冰锥术Lv5');
INSERT INTO `t_cfg_skill` VALUES ('456', '冰锥术Lv6');
INSERT INTO `t_cfg_skill` VALUES ('457', '冰锥术Lv7');
INSERT INTO `t_cfg_skill` VALUES ('458', '冰锥术Lv8');
INSERT INTO `t_cfg_skill` VALUES ('459', '冰锥术Lv9');
INSERT INTO `t_cfg_skill` VALUES ('460', '冰锥术Lv10');
INSERT INTO `t_cfg_skill` VALUES ('471', '冰封球Lv1');
INSERT INTO `t_cfg_skill` VALUES ('472', '冰封球Lv2');
INSERT INTO `t_cfg_skill` VALUES ('473', '冰封球Lv3');
INSERT INTO `t_cfg_skill` VALUES ('474', '冰封球Lv4');
INSERT INTO `t_cfg_skill` VALUES ('475', '冰封球Lv5');
INSERT INTO `t_cfg_skill` VALUES ('476', '冰封球Lv6');
INSERT INTO `t_cfg_skill` VALUES ('477', '冰封球Lv7');
INSERT INTO `t_cfg_skill` VALUES ('478', '冰封球Lv8');
INSERT INTO `t_cfg_skill` VALUES ('479', '冰封球Lv9');
INSERT INTO `t_cfg_skill` VALUES ('480', '冰封球Lv10');
INSERT INTO `t_cfg_skill` VALUES ('491', '多重冰锥术Lv1');
INSERT INTO `t_cfg_skill` VALUES ('492', '多重冰锥术Lv2');
INSERT INTO `t_cfg_skill` VALUES ('493', '多重冰锥术Lv3');
INSERT INTO `t_cfg_skill` VALUES ('494', '多重冰锥术Lv4');
INSERT INTO `t_cfg_skill` VALUES ('495', '多重冰锥术Lv5');
INSERT INTO `t_cfg_skill` VALUES ('496', '多重冰锥术Lv6');
INSERT INTO `t_cfg_skill` VALUES ('497', '多重冰锥术Lv7');
INSERT INTO `t_cfg_skill` VALUES ('498', '多重冰锥术Lv8');
INSERT INTO `t_cfg_skill` VALUES ('499', '多重冰锥术Lv9');
INSERT INTO `t_cfg_skill` VALUES ('500', '多重冰锥术Lv10');
INSERT INTO `t_cfg_skill` VALUES ('511', '暴风雪Lv1');
INSERT INTO `t_cfg_skill` VALUES ('512', '暴风雪Lv2');
INSERT INTO `t_cfg_skill` VALUES ('513', '暴风雪Lv3');
INSERT INTO `t_cfg_skill` VALUES ('514', '暴风雪Lv4');
INSERT INTO `t_cfg_skill` VALUES ('515', '暴风雪Lv5');
INSERT INTO `t_cfg_skill` VALUES ('516', '暴风雪Lv6');
INSERT INTO `t_cfg_skill` VALUES ('517', '暴风雪Lv7');
INSERT INTO `t_cfg_skill` VALUES ('518', '暴风雪Lv8');
INSERT INTO `t_cfg_skill` VALUES ('519', '暴风雪Lv9');
INSERT INTO `t_cfg_skill` VALUES ('520', '暴风雪Lv10');
INSERT INTO `t_cfg_skill` VALUES ('531', '冰霜新星Lv1');
INSERT INTO `t_cfg_skill` VALUES ('532', '冰霜新星Lv2');
INSERT INTO `t_cfg_skill` VALUES ('533', '冰霜新星Lv3');
INSERT INTO `t_cfg_skill` VALUES ('534', '冰霜新星Lv4');
INSERT INTO `t_cfg_skill` VALUES ('535', '冰霜新星Lv5');
INSERT INTO `t_cfg_skill` VALUES ('536', '冰霜新星Lv6');
INSERT INTO `t_cfg_skill` VALUES ('537', '冰霜新星Lv7');
INSERT INTO `t_cfg_skill` VALUES ('538', '冰霜新星Lv8');
INSERT INTO `t_cfg_skill` VALUES ('539', '冰霜新星Lv9');
INSERT INTO `t_cfg_skill` VALUES ('540', '冰霜新星Lv10');
INSERT INTO `t_cfg_skill` VALUES ('601', '烈焰之风Lv1');
INSERT INTO `t_cfg_skill` VALUES ('602', '烈焰之风Lv2');
INSERT INTO `t_cfg_skill` VALUES ('603', '烈焰之风Lv3');
INSERT INTO `t_cfg_skill` VALUES ('604', '烈焰之风Lv4');
INSERT INTO `t_cfg_skill` VALUES ('605', '烈焰之风Lv5');
INSERT INTO `t_cfg_skill` VALUES ('606', '烈焰之风Lv6');
INSERT INTO `t_cfg_skill` VALUES ('607', '烈焰之风Lv7');
INSERT INTO `t_cfg_skill` VALUES ('608', '烈焰之风Lv8');
INSERT INTO `t_cfg_skill` VALUES ('609', '烈焰之风Lv9');
INSERT INTO `t_cfg_skill` VALUES ('610', '烈焰之风Lv10');
INSERT INTO `t_cfg_skill` VALUES ('621', '烈焰死光Lv1');
INSERT INTO `t_cfg_skill` VALUES ('622', '烈焰死光Lv2');
INSERT INTO `t_cfg_skill` VALUES ('623', '烈焰死光Lv3');
INSERT INTO `t_cfg_skill` VALUES ('624', '烈焰死光Lv4');
INSERT INTO `t_cfg_skill` VALUES ('625', '烈焰死光Lv5');
INSERT INTO `t_cfg_skill` VALUES ('626', '烈焰死光Lv6');
INSERT INTO `t_cfg_skill` VALUES ('627', '烈焰死光Lv7');
INSERT INTO `t_cfg_skill` VALUES ('628', '烈焰死光Lv8');
INSERT INTO `t_cfg_skill` VALUES ('629', '烈焰死光Lv9');
INSERT INTO `t_cfg_skill` VALUES ('630', '烈焰死光Lv10');
INSERT INTO `t_cfg_skill` VALUES ('641', '火焰魔眼Lv1');
INSERT INTO `t_cfg_skill` VALUES ('642', '火焰魔眼Lv2');
INSERT INTO `t_cfg_skill` VALUES ('643', '火焰魔眼Lv3');
INSERT INTO `t_cfg_skill` VALUES ('644', '火焰魔眼Lv4');
INSERT INTO `t_cfg_skill` VALUES ('645', '火焰魔眼Lv5');
INSERT INTO `t_cfg_skill` VALUES ('646', '火焰魔眼Lv6');
INSERT INTO `t_cfg_skill` VALUES ('647', '火焰魔眼Lv7');
INSERT INTO `t_cfg_skill` VALUES ('648', '火焰魔眼Lv8');
INSERT INTO `t_cfg_skill` VALUES ('649', '火焰魔眼Lv9');
INSERT INTO `t_cfg_skill` VALUES ('650', '火焰魔眼Lv10');
INSERT INTO `t_cfg_skill` VALUES ('661', '火旋风Lv1');
INSERT INTO `t_cfg_skill` VALUES ('662', '火旋风Lv2');
INSERT INTO `t_cfg_skill` VALUES ('663', '火旋风Lv3');
INSERT INTO `t_cfg_skill` VALUES ('664', '火旋风Lv4');
INSERT INTO `t_cfg_skill` VALUES ('665', '火旋风Lv5');
INSERT INTO `t_cfg_skill` VALUES ('666', '火旋风Lv6');
INSERT INTO `t_cfg_skill` VALUES ('667', '火旋风Lv7');
INSERT INTO `t_cfg_skill` VALUES ('668', '火旋风Lv8');
INSERT INTO `t_cfg_skill` VALUES ('669', '火旋风Lv9');
INSERT INTO `t_cfg_skill` VALUES ('670', '火旋风Lv10');
INSERT INTO `t_cfg_skill` VALUES ('681', '天火陨石Lv1');
INSERT INTO `t_cfg_skill` VALUES ('682', '天火陨石Lv2');
INSERT INTO `t_cfg_skill` VALUES ('683', '天火陨石Lv3');
INSERT INTO `t_cfg_skill` VALUES ('684', '天火陨石Lv4');
INSERT INTO `t_cfg_skill` VALUES ('685', '天火陨石Lv5');
INSERT INTO `t_cfg_skill` VALUES ('686', '天火陨石Lv6');
INSERT INTO `t_cfg_skill` VALUES ('687', '天火陨石Lv7');
INSERT INTO `t_cfg_skill` VALUES ('688', '天火陨石Lv8');
INSERT INTO `t_cfg_skill` VALUES ('689', '天火陨石Lv9');
INSERT INTO `t_cfg_skill` VALUES ('690', '天火陨石Lv10');
INSERT INTO `t_cfg_skill` VALUES ('751', '白骨之魂Lv1');
INSERT INTO `t_cfg_skill` VALUES ('752', '白骨之魂Lv2');
INSERT INTO `t_cfg_skill` VALUES ('753', '白骨之魂Lv3');
INSERT INTO `t_cfg_skill` VALUES ('754', '白骨之魂Lv4');
INSERT INTO `t_cfg_skill` VALUES ('755', '白骨之魂Lv5');
INSERT INTO `t_cfg_skill` VALUES ('756', '白骨之魂Lv6');
INSERT INTO `t_cfg_skill` VALUES ('757', '白骨之魂Lv7');
INSERT INTO `t_cfg_skill` VALUES ('758', '白骨之魂Lv8');
INSERT INTO `t_cfg_skill` VALUES ('759', '白骨之魂Lv9');
INSERT INTO `t_cfg_skill` VALUES ('760', '白骨之魂Lv10');
INSERT INTO `t_cfg_skill` VALUES ('771', '召唤骷髅Lv1');
INSERT INTO `t_cfg_skill` VALUES ('772', '召唤骷髅Lv2');
INSERT INTO `t_cfg_skill` VALUES ('773', '召唤骷髅Lv3');
INSERT INTO `t_cfg_skill` VALUES ('774', '召唤骷髅Lv4');
INSERT INTO `t_cfg_skill` VALUES ('775', '召唤骷髅Lv5');
INSERT INTO `t_cfg_skill` VALUES ('776', '召唤骷髅Lv6');
INSERT INTO `t_cfg_skill` VALUES ('777', '召唤骷髅Lv7');
INSERT INTO `t_cfg_skill` VALUES ('778', '召唤骷髅Lv8');
INSERT INTO `t_cfg_skill` VALUES ('779', '召唤骷髅Lv9');
INSERT INTO `t_cfg_skill` VALUES ('780', '召唤骷髅Lv10');
INSERT INTO `t_cfg_skill` VALUES ('791', '剧毒新星Lv1');
INSERT INTO `t_cfg_skill` VALUES ('792', '剧毒新星Lv2');
INSERT INTO `t_cfg_skill` VALUES ('793', '剧毒新星Lv3');
INSERT INTO `t_cfg_skill` VALUES ('794', '剧毒新星Lv4');
INSERT INTO `t_cfg_skill` VALUES ('795', '剧毒新星Lv5');
INSERT INTO `t_cfg_skill` VALUES ('796', '剧毒新星Lv6');
INSERT INTO `t_cfg_skill` VALUES ('797', '剧毒新星Lv7');
INSERT INTO `t_cfg_skill` VALUES ('798', '剧毒新星Lv8');
INSERT INTO `t_cfg_skill` VALUES ('799', '剧毒新星Lv9');
INSERT INTO `t_cfg_skill` VALUES ('800', '剧毒新星Lv10');
INSERT INTO `t_cfg_skill` VALUES ('811', '召唤地狱火Lv1');
INSERT INTO `t_cfg_skill` VALUES ('812', '召唤地狱火Lv2');
INSERT INTO `t_cfg_skill` VALUES ('813', '召唤地狱火Lv3');
INSERT INTO `t_cfg_skill` VALUES ('814', '召唤地狱火Lv4');
INSERT INTO `t_cfg_skill` VALUES ('815', '召唤地狱火Lv5');
INSERT INTO `t_cfg_skill` VALUES ('816', '召唤地狱火Lv6');
INSERT INTO `t_cfg_skill` VALUES ('817', '召唤地狱火Lv7');
INSERT INTO `t_cfg_skill` VALUES ('818', '召唤地狱火Lv8');
INSERT INTO `t_cfg_skill` VALUES ('819', '召唤地狱火Lv9');
INSERT INTO `t_cfg_skill` VALUES ('820', '召唤地狱火Lv10');
INSERT INTO `t_cfg_skill` VALUES ('901', '飞刀Lv1');
INSERT INTO `t_cfg_skill` VALUES ('902', '飞刀Lv2');
INSERT INTO `t_cfg_skill` VALUES ('903', '飞刀Lv3');
INSERT INTO `t_cfg_skill` VALUES ('904', '飞刀Lv4');
INSERT INTO `t_cfg_skill` VALUES ('905', '飞刀Lv5');
INSERT INTO `t_cfg_skill` VALUES ('906', '飞刀Lv6');
INSERT INTO `t_cfg_skill` VALUES ('907', '飞刀Lv7');
INSERT INTO `t_cfg_skill` VALUES ('908', '飞刀Lv8');
INSERT INTO `t_cfg_skill` VALUES ('909', '飞刀Lv9');
INSERT INTO `t_cfg_skill` VALUES ('910', '飞刀Lv10');
INSERT INTO `t_cfg_skill` VALUES ('921', '旋转飞刃Lv1');
INSERT INTO `t_cfg_skill` VALUES ('922', '旋转飞刃Lv2');
INSERT INTO `t_cfg_skill` VALUES ('923', '旋转飞刃Lv3');
INSERT INTO `t_cfg_skill` VALUES ('924', '旋转飞刃Lv4');
INSERT INTO `t_cfg_skill` VALUES ('925', '旋转飞刃Lv5');
INSERT INTO `t_cfg_skill` VALUES ('926', '旋转飞刃Lv6');
INSERT INTO `t_cfg_skill` VALUES ('927', '旋转飞刃Lv7');
INSERT INTO `t_cfg_skill` VALUES ('928', '旋转飞刃Lv8');
INSERT INTO `t_cfg_skill` VALUES ('929', '旋转飞刃Lv9');
INSERT INTO `t_cfg_skill` VALUES ('930', '旋转飞刃Lv10');
INSERT INTO `t_cfg_skill` VALUES ('941', '闪电陷阱Lv1');
INSERT INTO `t_cfg_skill` VALUES ('942', '闪电陷阱Lv2');
INSERT INTO `t_cfg_skill` VALUES ('943', '闪电陷阱Lv3');
INSERT INTO `t_cfg_skill` VALUES ('944', '闪电陷阱Lv4');
INSERT INTO `t_cfg_skill` VALUES ('945', '闪电陷阱Lv5');
INSERT INTO `t_cfg_skill` VALUES ('946', '闪电陷阱Lv6');
INSERT INTO `t_cfg_skill` VALUES ('947', '闪电陷阱Lv7');
INSERT INTO `t_cfg_skill` VALUES ('948', '闪电陷阱Lv8');
INSERT INTO `t_cfg_skill` VALUES ('949', '闪电陷阱Lv9');
INSERT INTO `t_cfg_skill` VALUES ('950', '闪电陷阱Lv10');
INSERT INTO `t_cfg_skill` VALUES ('961', '千刃Lv1');
INSERT INTO `t_cfg_skill` VALUES ('962', '千刃Lv2');
INSERT INTO `t_cfg_skill` VALUES ('963', '千刃Lv3');
INSERT INTO `t_cfg_skill` VALUES ('964', '千刃Lv4');
INSERT INTO `t_cfg_skill` VALUES ('965', '千刃Lv5');
INSERT INTO `t_cfg_skill` VALUES ('966', '千刃Lv6');
INSERT INTO `t_cfg_skill` VALUES ('967', '千刃Lv7');
INSERT INTO `t_cfg_skill` VALUES ('968', '千刃Lv8');
INSERT INTO `t_cfg_skill` VALUES ('969', '千刃Lv9');
INSERT INTO `t_cfg_skill` VALUES ('970', '千刃Lv10');
INSERT INTO `t_cfg_skill` VALUES ('1051', '虎击Lv1');
INSERT INTO `t_cfg_skill` VALUES ('1052', '虎击Lv2');
INSERT INTO `t_cfg_skill` VALUES ('1053', '虎击Lv3');
INSERT INTO `t_cfg_skill` VALUES ('1054', '虎击Lv4');
INSERT INTO `t_cfg_skill` VALUES ('1055', '虎击Lv5');
INSERT INTO `t_cfg_skill` VALUES ('1056', '虎击Lv6');
INSERT INTO `t_cfg_skill` VALUES ('1057', '虎击Lv7');
INSERT INTO `t_cfg_skill` VALUES ('1058', '虎击Lv8');
INSERT INTO `t_cfg_skill` VALUES ('1059', '虎击Lv9');
INSERT INTO `t_cfg_skill` VALUES ('1060', '虎击Lv10');
INSERT INTO `t_cfg_skill` VALUES ('1071', '飞龙在天Lv1');
INSERT INTO `t_cfg_skill` VALUES ('1072', '飞龙在天Lv2');
INSERT INTO `t_cfg_skill` VALUES ('1073', '飞龙在天Lv3');
INSERT INTO `t_cfg_skill` VALUES ('1074', '飞龙在天Lv4');
INSERT INTO `t_cfg_skill` VALUES ('1075', '飞龙在天Lv5');
INSERT INTO `t_cfg_skill` VALUES ('1076', '飞龙在天Lv6');
INSERT INTO `t_cfg_skill` VALUES ('1077', '飞龙在天Lv7');
INSERT INTO `t_cfg_skill` VALUES ('1078', '飞龙在天Lv8');
INSERT INTO `t_cfg_skill` VALUES ('1079', '飞龙在天Lv9');
INSERT INTO `t_cfg_skill` VALUES ('1080', '飞龙在天Lv10');
INSERT INTO `t_cfg_skill` VALUES ('1111', '凤凰攻击Lv1');
INSERT INTO `t_cfg_skill` VALUES ('1112', '凤凰攻击Lv2');
INSERT INTO `t_cfg_skill` VALUES ('1113', '凤凰攻击Lv3');
INSERT INTO `t_cfg_skill` VALUES ('1114', '凤凰攻击Lv4');
INSERT INTO `t_cfg_skill` VALUES ('1115', '凤凰攻击Lv5');
INSERT INTO `t_cfg_skill` VALUES ('1116', '凤凰攻击Lv6');
INSERT INTO `t_cfg_skill` VALUES ('1117', '凤凰攻击Lv7');
INSERT INTO `t_cfg_skill` VALUES ('1118', '凤凰攻击Lv8');
INSERT INTO `t_cfg_skill` VALUES ('1119', '凤凰攻击Lv9');
INSERT INTO `t_cfg_skill` VALUES ('1120', '凤凰攻击Lv10');
INSERT INTO `t_cfg_skill` VALUES ('1131', '凤凰攻击Lv1');
INSERT INTO `t_cfg_skill` VALUES ('1132', '凤凰攻击Lv2');
INSERT INTO `t_cfg_skill` VALUES ('1133', '凤凰攻击Lv3');
INSERT INTO `t_cfg_skill` VALUES ('1134', '凤凰攻击Lv4');
INSERT INTO `t_cfg_skill` VALUES ('1135', '凤凰攻击Lv5');
INSERT INTO `t_cfg_skill` VALUES ('1136', '凤凰攻击Lv6');
INSERT INTO `t_cfg_skill` VALUES ('1137', '凤凰攻击Lv7');
INSERT INTO `t_cfg_skill` VALUES ('1138', '凤凰攻击Lv8');
INSERT INTO `t_cfg_skill` VALUES ('1139', '凤凰攻击Lv9');
INSERT INTO `t_cfg_skill` VALUES ('1140', '凤凰攻击Lv10');
INSERT INTO `t_cfg_skill` VALUES ('1151', '凤凰攻击Lv1');
INSERT INTO `t_cfg_skill` VALUES ('1152', '凤凰攻击Lv2');
INSERT INTO `t_cfg_skill` VALUES ('1153', '凤凰攻击Lv3');
INSERT INTO `t_cfg_skill` VALUES ('1154', '凤凰攻击Lv4');
INSERT INTO `t_cfg_skill` VALUES ('1155', '凤凰攻击Lv5');
INSERT INTO `t_cfg_skill` VALUES ('1156', '凤凰攻击Lv6');
INSERT INTO `t_cfg_skill` VALUES ('1157', '凤凰攻击Lv7');
INSERT INTO `t_cfg_skill` VALUES ('1158', '凤凰攻击Lv8');
INSERT INTO `t_cfg_skill` VALUES ('1159', '凤凰攻击Lv9');
INSERT INTO `t_cfg_skill` VALUES ('1160', '凤凰攻击Lv10');
INSERT INTO `t_cfg_skill` VALUES ('1201', '影击Lv1');
INSERT INTO `t_cfg_skill` VALUES ('1202', '影击Lv2');
INSERT INTO `t_cfg_skill` VALUES ('1203', '影击Lv3');
INSERT INTO `t_cfg_skill` VALUES ('1204', '影击Lv4');
INSERT INTO `t_cfg_skill` VALUES ('1205', '影击Lv5');
INSERT INTO `t_cfg_skill` VALUES ('1206', '影击Lv6');
INSERT INTO `t_cfg_skill` VALUES ('1207', '影击Lv7');
INSERT INTO `t_cfg_skill` VALUES ('1208', '影击Lv8');
INSERT INTO `t_cfg_skill` VALUES ('1209', '影击Lv9');
INSERT INTO `t_cfg_skill` VALUES ('1210', '影击Lv10');
INSERT INTO `t_cfg_skill` VALUES ('1221', '幻影之舞Lv1');
INSERT INTO `t_cfg_skill` VALUES ('1222', '幻影之舞Lv2');
INSERT INTO `t_cfg_skill` VALUES ('1223', '幻影之舞Lv3');
INSERT INTO `t_cfg_skill` VALUES ('1224', '幻影之舞Lv4');
INSERT INTO `t_cfg_skill` VALUES ('1225', '幻影之舞Lv5');
INSERT INTO `t_cfg_skill` VALUES ('1226', '幻影之舞Lv6');
INSERT INTO `t_cfg_skill` VALUES ('1227', '幻影之舞Lv7');
INSERT INTO `t_cfg_skill` VALUES ('1228', '幻影之舞Lv8');
INSERT INTO `t_cfg_skill` VALUES ('1229', '幻影之舞Lv9');
INSERT INTO `t_cfg_skill` VALUES ('1230', '幻影之舞Lv10');
INSERT INTO `t_cfg_skill` VALUES ('1261', '召唤影子Lv1');
INSERT INTO `t_cfg_skill` VALUES ('1262', '召唤影子Lv2');
INSERT INTO `t_cfg_skill` VALUES ('1263', '召唤影子Lv3');
INSERT INTO `t_cfg_skill` VALUES ('1264', '召唤影子Lv4');
INSERT INTO `t_cfg_skill` VALUES ('1265', '召唤影子Lv5');
INSERT INTO `t_cfg_skill` VALUES ('1266', '召唤影子Lv6');
INSERT INTO `t_cfg_skill` VALUES ('1267', '召唤影子Lv7');
INSERT INTO `t_cfg_skill` VALUES ('1268', '召唤影子Lv8');
INSERT INTO `t_cfg_skill` VALUES ('1269', '召唤影子Lv9');
INSERT INTO `t_cfg_skill` VALUES ('1270', '召唤影子Lv10');
INSERT INTO `t_cfg_skill` VALUES ('1351', '跳斩伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1352', '跳斩伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1353', '跳斩伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1354', '跳斩伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1355', '跳斩伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1356', '跳斩伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1357', '跳斩伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1358', '跳斩伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1359', '跳斩伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1360', '跳斩伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1371', '旋风斩伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1372', '旋风斩伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1373', '旋风斩伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1374', '旋风斩伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1375', '旋风斩伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1376', '旋风斩伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1377', '旋风斩伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1378', '旋风斩伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1379', '旋风斩伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1380', '旋风斩伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1551', '祝福之锤后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1552', '祝福之锤后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1553', '祝福之锤后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1554', '祝福之锤后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1555', '祝福之锤后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1556', '祝福之锤后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1557', '祝福之锤后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1558', '祝福之锤后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1559', '祝福之锤后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1560', '祝福之锤后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1571', '天堂之拳后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1572', '天堂之拳后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1573', '天堂之拳后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1574', '天堂之拳后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1575', '天堂之拳后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1576', '天堂之拳后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1577', '天堂之拳后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1578', '天堂之拳后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1579', '天堂之拳后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1580', '天堂之拳后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1651', '冰封球伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1652', '冰封球伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1653', '冰封球伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1654', '冰封球伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1655', '冰封球伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1656', '冰封球伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1657', '冰封球伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1658', '冰封球伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1659', '冰封球伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1660', '冰封球伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1671', '暴风雪伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1672', '暴风雪伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1673', '暴风雪伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1674', '暴风雪伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1675', '暴风雪伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1676', '暴风雪伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1677', '暴风雪伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1678', '暴风雪伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1679', '暴风雪伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1680', '暴风雪伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1771', '火旋风后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1772', '火旋风后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1773', '火旋风后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1774', '火旋风后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1775', '火旋风后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1776', '火旋风后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1777', '火旋风后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1778', '火旋风后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1779', '火旋风后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1780', '火旋风后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('1791', '天火陨石伤害和范围Lv1');
INSERT INTO `t_cfg_skill` VALUES ('1792', '天火陨石伤害和范围Lv2');
INSERT INTO `t_cfg_skill` VALUES ('1793', '天火陨石伤害和范围Lv3');
INSERT INTO `t_cfg_skill` VALUES ('1794', '天火陨石伤害和范围Lv4');
INSERT INTO `t_cfg_skill` VALUES ('1795', '天火陨石伤害和范围Lv5');
INSERT INTO `t_cfg_skill` VALUES ('1796', '天火陨石伤害和范围Lv6');
INSERT INTO `t_cfg_skill` VALUES ('1797', '天火陨石伤害和范围Lv7');
INSERT INTO `t_cfg_skill` VALUES ('1798', '天火陨石伤害和范围Lv8');
INSERT INTO `t_cfg_skill` VALUES ('1799', '天火陨石伤害和范围Lv9');
INSERT INTO `t_cfg_skill` VALUES ('1800', '天火陨石伤害和范围Lv10');
INSERT INTO `t_cfg_skill` VALUES ('1871', '召唤地狱火伤害和范围Lv1');
INSERT INTO `t_cfg_skill` VALUES ('1872', '召唤地狱火伤害和范围Lv2');
INSERT INTO `t_cfg_skill` VALUES ('1873', '召唤地狱火伤害和范围Lv3');
INSERT INTO `t_cfg_skill` VALUES ('1874', '召唤地狱火伤害和范围Lv4');
INSERT INTO `t_cfg_skill` VALUES ('1875', '召唤地狱火伤害和范围Lv5');
INSERT INTO `t_cfg_skill` VALUES ('1876', '召唤地狱火伤害和范围Lv6');
INSERT INTO `t_cfg_skill` VALUES ('1877', '召唤地狱火伤害和范围Lv7');
INSERT INTO `t_cfg_skill` VALUES ('1878', '召唤地狱火伤害和范围Lv8');
INSERT INTO `t_cfg_skill` VALUES ('1879', '召唤地狱火伤害和范围Lv9');
INSERT INTO `t_cfg_skill` VALUES ('1880', '召唤地狱火伤害和范围Lv10');
INSERT INTO `t_cfg_skill` VALUES ('2051', '旋转飞刃后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2052', '旋转飞刃后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2053', '旋转飞刃后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2054', '旋转飞刃后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2055', '旋转飞刃后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2056', '旋转飞刃后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2057', '旋转飞刃后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2058', '旋转飞刃后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2059', '旋转飞刃后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2060', '旋转飞刃后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2071', '闪电陷阱后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2072', '闪电陷阱后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2073', '闪电陷阱后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2074', '闪电陷阱后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2075', '闪电陷阱后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2076', '闪电陷阱后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2077', '闪电陷阱后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2078', '闪电陷阱后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2079', '闪电陷阱后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2080', '闪电陷阱后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2151', '幻影之舞后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2152', '幻影之舞后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2153', '幻影之舞后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2154', '幻影之舞后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2155', '幻影之舞后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2156', '幻影之舞后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2157', '幻影之舞后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2158', '幻影之舞后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2159', '幻影之舞后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2160', '幻影之舞后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2501', '远程怪物物理攻击');
INSERT INTO `t_cfg_skill` VALUES ('2502', '超近程怪物攻击');
INSERT INTO `t_cfg_skill` VALUES ('2503', '怪物物理攻击');
INSERT INTO `t_cfg_skill` VALUES ('2504', '怪物快速物理攻击');
INSERT INTO `t_cfg_skill` VALUES ('2505', '怪物诅咒物理攻击');
INSERT INTO `t_cfg_skill` VALUES ('2506', '怪物远程火球术');
INSERT INTO `t_cfg_skill` VALUES ('2507', '怪物剧毒新星');
INSERT INTO `t_cfg_skill` VALUES ('2508', '怪物暴风雪');
INSERT INTO `t_cfg_skill` VALUES ('2509', '怪物暴风雪伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2510', '怪物闪电陷阱');
INSERT INTO `t_cfg_skill` VALUES ('2511', '闪电陷阱后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('2512', '怪物传送');
INSERT INTO `t_cfg_skill` VALUES ('2513', '怪物火焰魔眼');
INSERT INTO `t_cfg_skill` VALUES ('2514', '怪物远程冰锥术');
INSERT INTO `t_cfg_skill` VALUES ('2515', '怪物远程白骨术');
INSERT INTO `t_cfg_skill` VALUES ('2516', 'BOSS远程白骨术');
INSERT INTO `t_cfg_skill` VALUES ('2517', 'BOSS中距离物理攻击');
INSERT INTO `t_cfg_skill` VALUES ('3001', '闪电箭矢Lv1');
INSERT INTO `t_cfg_skill` VALUES ('3002', '闪电箭矢Lv2');
INSERT INTO `t_cfg_skill` VALUES ('3003', '闪电箭矢Lv3');
INSERT INTO `t_cfg_skill` VALUES ('3004', '闪电箭矢Lv4');
INSERT INTO `t_cfg_skill` VALUES ('3005', '闪电箭矢Lv5');
INSERT INTO `t_cfg_skill` VALUES ('3006', '闪电箭矢Lv6');
INSERT INTO `t_cfg_skill` VALUES ('3007', '闪电箭矢Lv7');
INSERT INTO `t_cfg_skill` VALUES ('3008', '闪电箭矢Lv8');
INSERT INTO `t_cfg_skill` VALUES ('3009', '闪电箭矢Lv9');
INSERT INTO `t_cfg_skill` VALUES ('3010', '闪电箭矢Lv10');
INSERT INTO `t_cfg_skill` VALUES ('3021', '鹰击长空Lv1');
INSERT INTO `t_cfg_skill` VALUES ('3022', '鹰击长空Lv2');
INSERT INTO `t_cfg_skill` VALUES ('3023', '鹰击长空Lv3');
INSERT INTO `t_cfg_skill` VALUES ('3024', '鹰击长空Lv4');
INSERT INTO `t_cfg_skill` VALUES ('3025', '鹰击长空Lv5');
INSERT INTO `t_cfg_skill` VALUES ('3026', '鹰击长空Lv6');
INSERT INTO `t_cfg_skill` VALUES ('3027', '鹰击长空Lv7');
INSERT INTO `t_cfg_skill` VALUES ('3028', '鹰击长空Lv8');
INSERT INTO `t_cfg_skill` VALUES ('3029', '鹰击长空Lv9');
INSERT INTO `t_cfg_skill` VALUES ('3030', '鹰击长空Lv10');
INSERT INTO `t_cfg_skill` VALUES ('3041', '雷霆射击Lv1');
INSERT INTO `t_cfg_skill` VALUES ('3042', '雷霆射击Lv2');
INSERT INTO `t_cfg_skill` VALUES ('3043', '雷霆射击Lv3');
INSERT INTO `t_cfg_skill` VALUES ('3044', '雷霆射击Lv4');
INSERT INTO `t_cfg_skill` VALUES ('3045', '雷霆射击Lv5');
INSERT INTO `t_cfg_skill` VALUES ('3046', '雷霆射击Lv6');
INSERT INTO `t_cfg_skill` VALUES ('3047', '雷霆射击Lv7');
INSERT INTO `t_cfg_skill` VALUES ('3048', '雷霆射击Lv8');
INSERT INTO `t_cfg_skill` VALUES ('3049', '雷霆射击Lv9');
INSERT INTO `t_cfg_skill` VALUES ('3050', '雷霆射击Lv10');
INSERT INTO `t_cfg_skill` VALUES ('3061', '弱点打击Lv1');
INSERT INTO `t_cfg_skill` VALUES ('3062', '弱点打击Lv2');
INSERT INTO `t_cfg_skill` VALUES ('3063', '弱点打击Lv3');
INSERT INTO `t_cfg_skill` VALUES ('3064', '弱点打击Lv4');
INSERT INTO `t_cfg_skill` VALUES ('3065', '弱点打击Lv5');
INSERT INTO `t_cfg_skill` VALUES ('3066', '弱点打击Lv6');
INSERT INTO `t_cfg_skill` VALUES ('3067', '弱点打击Lv7');
INSERT INTO `t_cfg_skill` VALUES ('3068', '弱点打击Lv8');
INSERT INTO `t_cfg_skill` VALUES ('3069', '弱点打击Lv9');
INSERT INTO `t_cfg_skill` VALUES ('3070', '弱点打击Lv10');
INSERT INTO `t_cfg_skill` VALUES ('3101', '雷霆射击后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('3102', '雷霆射击后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('3103', '雷霆射击后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('3104', '雷霆射击后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('3105', '雷霆射击后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('3106', '雷霆射击后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('3107', '雷霆射击后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('3108', '雷霆射击后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('3109', '雷霆射击后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('3110', '雷霆射击后续伤害和范围');
INSERT INTO `t_cfg_skill` VALUES ('3201', '雷霆肆虐Lv1');
INSERT INTO `t_cfg_skill` VALUES ('3202', '雷霆肆虐Lv2');
INSERT INTO `t_cfg_skill` VALUES ('3203', '雷霆肆虐Lv3');
INSERT INTO `t_cfg_skill` VALUES ('3204', '雷霆肆虐Lv4');
INSERT INTO `t_cfg_skill` VALUES ('3205', '雷霆肆虐Lv5');
INSERT INTO `t_cfg_skill` VALUES ('3206', '雷霆肆虐Lv6');
INSERT INTO `t_cfg_skill` VALUES ('3207', '雷霆肆虐Lv7');
INSERT INTO `t_cfg_skill` VALUES ('3208', '雷霆肆虐Lv8');
INSERT INTO `t_cfg_skill` VALUES ('3209', '雷霆肆虐Lv9');
INSERT INTO `t_cfg_skill` VALUES ('3210', '雷霆肆虐Lv10');
INSERT INTO `t_cfg_skill` VALUES ('3301', '先祖之魂2件Lv1');
INSERT INTO `t_cfg_skill` VALUES ('3302', '先祖之魂2件Lv2');
INSERT INTO `t_cfg_skill` VALUES ('3303', '先祖之魂2件Lv3');
INSERT INTO `t_cfg_skill` VALUES ('3304', '先祖之魂2件Lv4');
INSERT INTO `t_cfg_skill` VALUES ('3305', '先祖之魂2件Lv5');
INSERT INTO `t_cfg_skill` VALUES ('3306', '先祖之魂2件Lv6');
INSERT INTO `t_cfg_skill` VALUES ('3307', '先祖之魂2件Lv7');
INSERT INTO `t_cfg_skill` VALUES ('3308', '先祖之魂2件Lv8');
INSERT INTO `t_cfg_skill` VALUES ('3309', '先祖之魂2件Lv9');
INSERT INTO `t_cfg_skill` VALUES ('3310', '先祖之魂2件Lv10');
INSERT INTO `t_cfg_skill` VALUES ('3321', '御法者2件Lv1');
INSERT INTO `t_cfg_skill` VALUES ('3322', '御法者2件Lv2');
INSERT INTO `t_cfg_skill` VALUES ('3323', '御法者2件Lv3');
INSERT INTO `t_cfg_skill` VALUES ('3324', '御法者2件Lv4');
INSERT INTO `t_cfg_skill` VALUES ('3325', '御法者2件Lv5');
INSERT INTO `t_cfg_skill` VALUES ('3326', '御法者2件Lv6');
INSERT INTO `t_cfg_skill` VALUES ('3327', '御法者2件Lv7');
INSERT INTO `t_cfg_skill` VALUES ('3328', '御法者2件Lv8');
INSERT INTO `t_cfg_skill` VALUES ('3329', '御法者2件Lv9');
INSERT INTO `t_cfg_skill` VALUES ('3330', '御法者2件Lv10');
INSERT INTO `t_cfg_skill` VALUES ('3341', '暗影猎杀2件Lv1');
INSERT INTO `t_cfg_skill` VALUES ('3342', '暗影猎杀2件Lv2');
INSERT INTO `t_cfg_skill` VALUES ('3343', '暗影猎杀2件Lv3');
INSERT INTO `t_cfg_skill` VALUES ('3344', '暗影猎杀2件Lv4');
INSERT INTO `t_cfg_skill` VALUES ('3345', '暗影猎杀2件Lv5');
INSERT INTO `t_cfg_skill` VALUES ('3346', '暗影猎杀2件Lv6');
INSERT INTO `t_cfg_skill` VALUES ('3347', '暗影猎杀2件Lv7');
INSERT INTO `t_cfg_skill` VALUES ('3348', '暗影猎杀2件Lv8');
INSERT INTO `t_cfg_skill` VALUES ('3349', '暗影猎杀2件Lv9');
INSERT INTO `t_cfg_skill` VALUES ('3350', '暗影猎杀2件Lv10');
INSERT INTO `t_cfg_skill` VALUES ('3401', '火炮');
INSERT INTO `t_cfg_skill` VALUES ('3421', '疾驰');
INSERT INTO `t_cfg_skill` VALUES ('3441', '装甲');
INSERT INTO `t_cfg_skill` VALUES ('3461', '下车');
INSERT INTO `t_cfg_skill` VALUES ('3501', '基本剑术Lv1');
INSERT INTO `t_cfg_skill` VALUES ('3502', '基本剑术Lv2');
INSERT INTO `t_cfg_skill` VALUES ('3503', '基本剑术Lv3');
INSERT INTO `t_cfg_skill` VALUES ('3504', '基本剑术Lv4');
INSERT INTO `t_cfg_skill` VALUES ('3505', '基本剑术Lv5');
INSERT INTO `t_cfg_skill` VALUES ('3506', '基本剑术Lv6');
INSERT INTO `t_cfg_skill` VALUES ('3507', '基本剑术Lv7');
INSERT INTO `t_cfg_skill` VALUES ('3508', '基本剑术Lv8');
INSERT INTO `t_cfg_skill` VALUES ('3509', '基本剑术Lv9');
INSERT INTO `t_cfg_skill` VALUES ('3510', '基本剑术Lv10');

-- ----------------------------
-- Table structure for `t_cfg_task`
-- ----------------------------
DROP TABLE IF EXISTS `t_cfg_task`;
CREATE TABLE `t_cfg_task` (
  `taskId` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `level` int(11) NOT NULL,
  `target` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of t_cfg_task
-- ----------------------------
INSERT INTO `t_cfg_task` VALUES ('10000', '清理妖兽', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10001', '圣妖传说', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10002', '腐化气息', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10003', '战甲加身', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10004', '邪恶入侵', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10005', '人族灾祸', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10006', '救赎之路', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10007', '发现密道', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10008', '到达圣城', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10009', '联军传说', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10010', '逃难之人', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10011', '寻找宠物', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10012', '希望种子', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10013', '幻象空间', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10014', '试炼之地', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10015', '污染逼近', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10016', '留在这里', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10017', '王的永生', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10018', '魔兽大军', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10019', '绝望选择', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10020', '骷髅王', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10021', '死里逃生', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10022', '元宝回收', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10023', '新的消息', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10024', '装备回收', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10025', '空间之力', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10026', '请活下来', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10027', '蛮荒之地', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10028', '宠物之威', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10029', '弱鸡主人', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10030', '魔法生物', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10031', '邪恶魔法', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10032', '最后防线', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10033', '毁灭重生', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10034', '炼狱骑士', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10035', '劫后余生', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10036', '装备回收', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10037', '防御之道', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10038', '等级提升', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10039', '装备回收', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10040', '提升宠物', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10041', '灵丹妙药', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10042', '困惑来源', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10043', '精神治疗', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10044', '等级提升', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10045', '整装待发', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10046', '初入地宫', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10047', '亡灵法师', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10048', '新的发现', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10049', '地宫规则', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10050', '力量爆发', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10051', '力量困惑', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10052', '未知世界', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10053', '真血试炼', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10054', '装备回收', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10055', '寻找答案', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10056', '等级提升', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10057', '再回地宫', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10058', '人间失格', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10059', '迷失心性', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10060', '杀戮之心', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10061', '彼岸森林', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10062', '黑夜前行', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10063', '毁灭之王', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10064', '装备回收', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10065', '力量源泉', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10066', '等级提升', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10067', '新的信仰', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10068', '赏金任务', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10069', '月光杯酒', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10070', '再战荒原', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10071', '装备回收', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10072', '酒后往事', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10073', '宠物提升', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10074', '清风为伴', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10075', '噩耗来袭', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10076', '等级提升', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10077', '装备回收', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10078', '恐慌弥漫', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10079', '战前准备', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10080', '争霸伊始', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10081', '震撼人心', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10082', '新的敌人', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10083', '心中惆怅', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10084', '等级提升', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10085', '孤单手帕', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10086', '心思杜明', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10087', '黎明号角', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10088', '真正试炼', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10089', '忐忑命运', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10090', '提升宠物', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10091', '傲娇宠物', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10092', '穿戴装备', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10093', '未知探索', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10094', '诗和远方', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10095', '命运选择', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10096', '荒原历练', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10097', '剑震山河', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10098', '魔兽传说', '1', '');
INSERT INTO `t_cfg_task` VALUES ('10099', '变强奥秘', '1', '');
INSERT INTO `t_cfg_task` VALUES ('30000', '2阶宠物', '9999', '');
INSERT INTO `t_cfg_task` VALUES ('30001', '4阶宠物', '9999', '');
INSERT INTO `t_cfg_task` VALUES ('30002', '7阶宠物', '9999', '');
INSERT INTO `t_cfg_task` VALUES ('30004', '见习武者', '9999', '');
INSERT INTO `t_cfg_task` VALUES ('30005', '超凡入圣', '9999', '');
INSERT INTO `t_cfg_task` VALUES ('30006', '极品装备', '9999', '');
INSERT INTO `t_cfg_task` VALUES ('30007', '极品装备', '9999', '');
INSERT INTO `t_cfg_task` VALUES ('30008', '极品装备', '9999', '');
INSERT INTO `t_cfg_task` VALUES ('19999', '金币符文', '110', '');
INSERT INTO `t_cfg_task` VALUES ('20000', '金币符文', '110', '');
INSERT INTO `t_cfg_task` VALUES ('20001', '金币符文', '110', '');
INSERT INTO `t_cfg_task` VALUES ('20002', '金币符文', '110', '');
INSERT INTO `t_cfg_task` VALUES ('20003', '金币符文', '110', '');
INSERT INTO `t_cfg_task` VALUES ('20004', '金币符文', '110', '');
INSERT INTO `t_cfg_task` VALUES ('20005', '金币符文', '110', '');
INSERT INTO `t_cfg_task` VALUES ('20006', '金币符文', '110', '');
INSERT INTO `t_cfg_task` VALUES ('20007', '金币符文', '110', '');
INSERT INTO `t_cfg_task` VALUES ('20008', '金币符文', '110', '');
INSERT INTO `t_cfg_task` VALUES ('20009', '金币符文', '110', '');
INSERT INTO `t_cfg_task` VALUES ('20010', '金币符文', '110', '');
INSERT INTO `t_cfg_task` VALUES ('20011', '金币符文', '110', '');
INSERT INTO `t_cfg_task` VALUES ('20012', '金币符文', '110', '');
INSERT INTO `t_cfg_task` VALUES ('20013', '金币符文', '150', '');
INSERT INTO `t_cfg_task` VALUES ('20014', '金币符文', '150', '');
INSERT INTO `t_cfg_task` VALUES ('20015', '金币符文', '150', '');
INSERT INTO `t_cfg_task` VALUES ('20016', '金币符文', '150', '');
INSERT INTO `t_cfg_task` VALUES ('20017', '金币符文', '150', '');
INSERT INTO `t_cfg_task` VALUES ('20018', '金币符文', '150', '');
INSERT INTO `t_cfg_task` VALUES ('20019', '金币符文', '150', '');
INSERT INTO `t_cfg_task` VALUES ('20020', '金币符文', '150', '');
INSERT INTO `t_cfg_task` VALUES ('20021', '金币符文', '150', '');
INSERT INTO `t_cfg_task` VALUES ('20022', '金币符文', '150', '');
INSERT INTO `t_cfg_task` VALUES ('20023', '金币符文', '150', '');
INSERT INTO `t_cfg_task` VALUES ('20024', '金币符文', '150', '');
INSERT INTO `t_cfg_task` VALUES ('20025', '金币符文', '150', '');
INSERT INTO `t_cfg_task` VALUES ('20026', '金币符文', '150', '');
INSERT INTO `t_cfg_task` VALUES ('20027', '金币符文', '150', '');
INSERT INTO `t_cfg_task` VALUES ('20028', '金币符文', '150', '');
INSERT INTO `t_cfg_task` VALUES ('20029', '金币符文', '200', '');
INSERT INTO `t_cfg_task` VALUES ('20030', '金币符文', '200', '');
INSERT INTO `t_cfg_task` VALUES ('20031', '金币符文', '200', '');
INSERT INTO `t_cfg_task` VALUES ('20032', '金币符文', '200', '');
INSERT INTO `t_cfg_task` VALUES ('20033', '金币符文', '200', '');
INSERT INTO `t_cfg_task` VALUES ('20034', '金币符文', '200', '');
INSERT INTO `t_cfg_task` VALUES ('20035', '金币符文', '200', '');
INSERT INTO `t_cfg_task` VALUES ('20036', '金币符文', '200', '');
INSERT INTO `t_cfg_task` VALUES ('20037', '金币符文', '200', '');
INSERT INTO `t_cfg_task` VALUES ('20038', '金币符文', '200', '');
INSERT INTO `t_cfg_task` VALUES ('20039', '金币符文', '200', '');
INSERT INTO `t_cfg_task` VALUES ('20040', '金币符文', '200', '');
INSERT INTO `t_cfg_task` VALUES ('20041', '金币符文', '200', '');
INSERT INTO `t_cfg_task` VALUES ('20042', '金币符文', '200', '');
INSERT INTO `t_cfg_task` VALUES ('20043', '金币符文', '200', '');
INSERT INTO `t_cfg_task` VALUES ('20044', '金币符文', '200', '');
INSERT INTO `t_cfg_task` VALUES ('20045', '金币符文', '200', '');
INSERT INTO `t_cfg_task` VALUES ('20046', '金币符文', '200', '');
INSERT INTO `t_cfg_task` VALUES ('20047', '金币符文', '200', '');
INSERT INTO `t_cfg_task` VALUES ('20048', '金币符文', '300', '');
INSERT INTO `t_cfg_task` VALUES ('20049', '金币符文', '300', '');
INSERT INTO `t_cfg_task` VALUES ('20050', '金币符文', '300', '');
INSERT INTO `t_cfg_task` VALUES ('20051', '金币符文', '300', '');
INSERT INTO `t_cfg_task` VALUES ('20052', '金币符文', '300', '');
INSERT INTO `t_cfg_task` VALUES ('20053', '金币符文', '300', '');
INSERT INTO `t_cfg_task` VALUES ('20054', '金币符文', '300', '');
INSERT INTO `t_cfg_task` VALUES ('20055', '金币符文', '300', '');
INSERT INTO `t_cfg_task` VALUES ('20056', '金币符文', '300', '');
INSERT INTO `t_cfg_task` VALUES ('20057', '金币符文', '300', '');
INSERT INTO `t_cfg_task` VALUES ('20058', '金币符文', '300', '');
INSERT INTO `t_cfg_task` VALUES ('20059', '金币符文', '300', '');
INSERT INTO `t_cfg_task` VALUES ('20060', '金币符文', '300', '');
INSERT INTO `t_cfg_task` VALUES ('20061', '金币符文', '300', '');
INSERT INTO `t_cfg_task` VALUES ('20062', '金币符文', '300', '');
INSERT INTO `t_cfg_task` VALUES ('20063', '金币符文', '300', '');
INSERT INTO `t_cfg_task` VALUES ('20064', '金币符文', '300', '');
INSERT INTO `t_cfg_task` VALUES ('20065', '金币符文', '300', '');
INSERT INTO `t_cfg_task` VALUES ('20066', '金币符文', '300', '');
INSERT INTO `t_cfg_task` VALUES ('20067', '金币符文', '300', '');
INSERT INTO `t_cfg_task` VALUES ('20068', '金币符文', '300', '');
INSERT INTO `t_cfg_task` VALUES ('20069', '金币符文', '300', '');
INSERT INTO `t_cfg_task` VALUES ('20070', '金币符文', '300', '');
INSERT INTO `t_cfg_task` VALUES ('20071', '金币符文', '300', '');
INSERT INTO `t_cfg_task` VALUES ('20072', '金币符文', '300', '');
INSERT INTO `t_cfg_task` VALUES ('20073', '金币符文', '400', '');
INSERT INTO `t_cfg_task` VALUES ('20074', '金币符文', '400', '');
INSERT INTO `t_cfg_task` VALUES ('20075', '金币符文', '400', '');
INSERT INTO `t_cfg_task` VALUES ('20076', '金币符文', '400', '');
INSERT INTO `t_cfg_task` VALUES ('20077', '金币符文', '400', '');
INSERT INTO `t_cfg_task` VALUES ('20078', '金币符文', '400', '');
INSERT INTO `t_cfg_task` VALUES ('20079', '金币符文', '400', '');
INSERT INTO `t_cfg_task` VALUES ('20080', '金币符文', '400', '');
INSERT INTO `t_cfg_task` VALUES ('20081', '金币符文', '400', '');
INSERT INTO `t_cfg_task` VALUES ('20082', '金币符文', '400', '');
INSERT INTO `t_cfg_task` VALUES ('20083', '金币符文', '400', '');
INSERT INTO `t_cfg_task` VALUES ('20084', '金币符文', '400', '');
INSERT INTO `t_cfg_task` VALUES ('20085', '金币符文', '400', '');
INSERT INTO `t_cfg_task` VALUES ('20086', '金币符文', '400', '');
INSERT INTO `t_cfg_task` VALUES ('20087', '金币符文', '400', '');
INSERT INTO `t_cfg_task` VALUES ('20088', '金币符文', '400', '');
INSERT INTO `t_cfg_task` VALUES ('20089', '金币符文', '400', '');
INSERT INTO `t_cfg_task` VALUES ('20090', '金币符文', '400', '');
INSERT INTO `t_cfg_task` VALUES ('20091', '金币符文', '400', '');
INSERT INTO `t_cfg_task` VALUES ('20092', '金币符文', '400', '');
INSERT INTO `t_cfg_task` VALUES ('20093', '金币符文', '400', '');
INSERT INTO `t_cfg_task` VALUES ('20094', '金币符文', '400', '');
INSERT INTO `t_cfg_task` VALUES ('20095', '金币符文', '400', '');
INSERT INTO `t_cfg_task` VALUES ('20096', '金币符文', '400', '');
INSERT INTO `t_cfg_task` VALUES ('20097', '金币符文', '400', '');
INSERT INTO `t_cfg_task` VALUES ('20098', '金币符文', '500', '');
INSERT INTO `t_cfg_task` VALUES ('20099', '金币符文', '500', '');
INSERT INTO `t_cfg_task` VALUES ('20100', '金币符文', '500', '');
INSERT INTO `t_cfg_task` VALUES ('20101', '金币符文', '500', '');
INSERT INTO `t_cfg_task` VALUES ('20102', '金币符文', '500', '');
INSERT INTO `t_cfg_task` VALUES ('20103', '金币符文', '500', '');
INSERT INTO `t_cfg_task` VALUES ('20104', '金币符文', '500', '');
INSERT INTO `t_cfg_task` VALUES ('20105', '金币符文', '500', '');
INSERT INTO `t_cfg_task` VALUES ('20106', '金币符文', '500', '');
INSERT INTO `t_cfg_task` VALUES ('20107', '金币符文', '500', '');
INSERT INTO `t_cfg_task` VALUES ('20108', '金币符文', '500', '');
INSERT INTO `t_cfg_task` VALUES ('20109', '金币符文', '500', '');
INSERT INTO `t_cfg_task` VALUES ('20110', '金币符文', '500', '');
INSERT INTO `t_cfg_task` VALUES ('20111', '金币符文', '500', '');
INSERT INTO `t_cfg_task` VALUES ('20112', '金币符文', '500', '');
INSERT INTO `t_cfg_task` VALUES ('20113', '金币符文', '500', '');
INSERT INTO `t_cfg_task` VALUES ('20114', '金币符文', '500', '');
INSERT INTO `t_cfg_task` VALUES ('20115', '金币符文', '500', '');
INSERT INTO `t_cfg_task` VALUES ('20116', '金币符文', '500', '');
INSERT INTO `t_cfg_task` VALUES ('20117', '金币符文', '500', '');
INSERT INTO `t_cfg_task` VALUES ('20118', '金币符文', '500', '');
INSERT INTO `t_cfg_task` VALUES ('20119', '金币符文', '500', '');
INSERT INTO `t_cfg_task` VALUES ('20120', '金币符文', '500', '');
INSERT INTO `t_cfg_task` VALUES ('20121', '金币符文', '500', '');
INSERT INTO `t_cfg_task` VALUES ('20122', '金币符文', '500', '');
INSERT INTO `t_cfg_task` VALUES ('20123', '金币符文', '600', '');
INSERT INTO `t_cfg_task` VALUES ('20124', '金币符文', '600', '');
INSERT INTO `t_cfg_task` VALUES ('20125', '金币符文', '600', '');
INSERT INTO `t_cfg_task` VALUES ('20126', '金币符文', '600', '');
INSERT INTO `t_cfg_task` VALUES ('20127', '金币符文', '600', '');
INSERT INTO `t_cfg_task` VALUES ('20128', '金币符文', '600', '');
INSERT INTO `t_cfg_task` VALUES ('20129', '金币符文', '600', '');
INSERT INTO `t_cfg_task` VALUES ('20130', '金币符文', '600', '');
INSERT INTO `t_cfg_task` VALUES ('20131', '金币符文', '600', '');
INSERT INTO `t_cfg_task` VALUES ('20132', '金币符文', '600', '');
INSERT INTO `t_cfg_task` VALUES ('20133', '金币符文', '600', '');
INSERT INTO `t_cfg_task` VALUES ('20134', '金币符文', '600', '');
INSERT INTO `t_cfg_task` VALUES ('20135', '金币符文', '600', '');
INSERT INTO `t_cfg_task` VALUES ('20136', '金币符文', '600', '');
INSERT INTO `t_cfg_task` VALUES ('20137', '金币符文', '600', '');
INSERT INTO `t_cfg_task` VALUES ('20138', '金币符文', '600', '');
INSERT INTO `t_cfg_task` VALUES ('20139', '金币符文', '600', '');
INSERT INTO `t_cfg_task` VALUES ('20140', '金币符文', '600', '');
INSERT INTO `t_cfg_task` VALUES ('20141', '金币符文', '600', '');
INSERT INTO `t_cfg_task` VALUES ('20142', '金币符文', '600', '');
INSERT INTO `t_cfg_task` VALUES ('20143', '金币符文', '600', '');
INSERT INTO `t_cfg_task` VALUES ('20144', '金币符文', '600', '');
INSERT INTO `t_cfg_task` VALUES ('20145', '金币符文', '600', '');
INSERT INTO `t_cfg_task` VALUES ('20146', '金币符文', '600', '');
INSERT INTO `t_cfg_task` VALUES ('20147', '金币符文', '600', '');
INSERT INTO `t_cfg_task` VALUES ('25001', '押镖任务', '130', '');
INSERT INTO `t_cfg_task` VALUES ('25002', '押镖任务', '130', '');
INSERT INTO `t_cfg_task` VALUES ('25003', '押镖任务', '130', '');
INSERT INTO `t_cfg_task` VALUES ('25004', '押镖任务', '130', '');
INSERT INTO `t_cfg_task` VALUES ('25005', '押镖任务', '130', '');
INSERT INTO `t_cfg_task` VALUES ('26001', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26002', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26003', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26004', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26005', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26006', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26007', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26008', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26009', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26010', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26011', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26012', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26013', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26014', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26015', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26016', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26017', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26018', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26019', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26020', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26021', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26022', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26023', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26024', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26025', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26026', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26027', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26028', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26029', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26030', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26031', '回收任务', '200', '');
INSERT INTO `t_cfg_task` VALUES ('26032', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26033', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26034', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26035', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26036', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26037', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26038', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26039', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26040', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26041', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26042', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26043', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26044', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26045', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26046', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26047', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26048', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26049', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26050', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26051', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26052', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26053', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26054', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26055', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26056', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26057', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26058', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26059', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26060', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26061', '回收任务', '300', '');
INSERT INTO `t_cfg_task` VALUES ('26062', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26063', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26064', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26065', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26066', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26067', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26068', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26069', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26070', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26071', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26072', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26073', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26074', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26075', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26076', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26077', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26078', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26079', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26080', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26081', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26082', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26083', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26084', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26085', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26086', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26087', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26088', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26089', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26090', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26091', '回收任务', '400', '');
INSERT INTO `t_cfg_task` VALUES ('26092', '回收任务', '500', '');
INSERT INTO `t_cfg_task` VALUES ('26093', '回收任务', '500', '');
INSERT INTO `t_cfg_task` VALUES ('26094', '回收任务', '500', '');
INSERT INTO `t_cfg_task` VALUES ('26095', '回收任务', '500', '');
INSERT INTO `t_cfg_task` VALUES ('26096', '回收任务', '500', '');
INSERT INTO `t_cfg_task` VALUES ('26097', '回收任务', '500', '');
INSERT INTO `t_cfg_task` VALUES ('26098', '回收任务', '500', '');
INSERT INTO `t_cfg_task` VALUES ('26099', '回收任务', '500', '');
INSERT INTO `t_cfg_task` VALUES ('26100', '回收任务', '500', '');
INSERT INTO `t_cfg_task` VALUES ('26101', '回收任务', '500', '');
INSERT INTO `t_cfg_task` VALUES ('26102', '回收任务', '500', '');
INSERT INTO `t_cfg_task` VALUES ('26103', '回收任务', '500', '');
INSERT INTO `t_cfg_task` VALUES ('26104', '回收任务', '500', '');
INSERT INTO `t_cfg_task` VALUES ('26105', '回收任务', '500', '');
INSERT INTO `t_cfg_task` VALUES ('26106', '回收任务', '500', '');
INSERT INTO `t_cfg_task` VALUES ('26107', '回收任务', '500', '');
INSERT INTO `t_cfg_task` VALUES ('26108', '回收任务', '500', '');
INSERT INTO `t_cfg_task` VALUES ('26109', '回收任务', '500', '');
INSERT INTO `t_cfg_task` VALUES ('26110', '回收任务', '500', '');
INSERT INTO `t_cfg_task` VALUES ('26111', '回收任务', '500', '');
INSERT INTO `t_cfg_task` VALUES ('26112', '回收任务', '500', '');
INSERT INTO `t_cfg_task` VALUES ('26113', '回收任务', '500', '');
INSERT INTO `t_cfg_task` VALUES ('26114', '回收任务', '500', '');
INSERT INTO `t_cfg_task` VALUES ('26115', '回收任务', '500', '');
INSERT INTO `t_cfg_task` VALUES ('26116', '回收任务', '600', '');
INSERT INTO `t_cfg_task` VALUES ('26117', '回收任务', '600', '');
INSERT INTO `t_cfg_task` VALUES ('26118', '回收任务', '600', '');
INSERT INTO `t_cfg_task` VALUES ('26119', '回收任务', '600', '');
INSERT INTO `t_cfg_task` VALUES ('26120', '回收任务', '600', '');
INSERT INTO `t_cfg_task` VALUES ('26121', '回收任务', '600', '');
INSERT INTO `t_cfg_task` VALUES ('26122', '回收任务', '600', '');
INSERT INTO `t_cfg_task` VALUES ('26123', '回收任务', '600', '');
INSERT INTO `t_cfg_task` VALUES ('26124', '回收任务', '600', '');
INSERT INTO `t_cfg_task` VALUES ('26125', '回收任务', '600', '');
INSERT INTO `t_cfg_task` VALUES ('26126', '回收任务', '600', '');
INSERT INTO `t_cfg_task` VALUES ('26127', '回收任务', '600', '');
INSERT INTO `t_cfg_task` VALUES ('26128', '回收任务', '600', '');
INSERT INTO `t_cfg_task` VALUES ('26129', '回收任务', '600', '');
INSERT INTO `t_cfg_task` VALUES ('26130', '回收任务', '600', '');
INSERT INTO `t_cfg_task` VALUES ('26131', '回收任务', '600', '');
INSERT INTO `t_cfg_task` VALUES ('26132', '回收任务', '600', '');
INSERT INTO `t_cfg_task` VALUES ('26133', '回收任务', '600', '');
INSERT INTO `t_cfg_task` VALUES ('26134', '回收任务', '600', '');
INSERT INTO `t_cfg_task` VALUES ('26135', '回收任务', '600', '');
INSERT INTO `t_cfg_task` VALUES ('26136', '回收任务', '600', '');
